apiVersion: v1
kind: Pod
metadata: 
    name: ip-app-cm
spec:
  containers:
    - name: ip-app
      image: gurubasavaraj/ip_app:latest
      ports:
      - containerPort: 80
      env:                                  #env always comes under container level   
      - name: ENVIRONMENT                   #here it has to be uppercase
        valueFrom:
            configMapKeyRef:                #mapping value from configmap.yml
                    name: my-cm             #my-cm is the name of configmap.yml
                    key: env
      - name: APPLICATION
        valueFrom:
            configMapKeyRef:
                    name: my-cm
                    key: app
