apiVersion: v1
kind: Pod
metadata:
<<<<<<< HEAD
    name: my-pod-secrets-configmaps 
spec: 
    containers:
    - name: ip-app 
      image: gurubasavaraj/ip_app:latest 
      ports:
      - containerPort: 80
      volumeMounts:                          #Now mount volume
      - name: config-volume                     #Volume name of the config-volume which we want to mount. Volume name is below mentioned
        mountPath: "/app/volume/configmap"      #the path where we want to mount inside the container
      - name: secret-volume                     #Volume name of the secret-volume, which is below mentioned        
        mountPath: "/app/volume/secret"         
    volumes:
    - name: config-volume 
      configMap: 
         name: my-vol-cm
    - name: secret-volume 
      secret:
         secretName: my-vol-secret           
         #volumes:                                 #First creat the volume            
         #    - name: config-volume
         #configMap:                             #creating volume from configmap  
         # name: my-vol-cm                    #objectname of config.yml                               
         #    - name: secret-volume
         #secret:
         # secretName: my-vol-secret
=======
    name: my-pod-secrets-configmaps
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app:2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: '/app/volume/configmap'
    - name: secret-volume
      mountPath: '/app/volume/secret'  
  volumes:
  - name: config-volume 
    configMap: 
       name: my-vol-cm
  - name: secret-volume 
    secret:
       secretName: my-vol-secret       
>>>>>>> c5f0c25b3daafd86b13c13c28d8373cb3d9c29db
