apiVersion: v1
kind: Secret
metadata: 
    name: my-vol-secret
type: Opaque                       #type of the secret we have have to mention here
data:
   app.conf: |                     #kubernetes standard
      Z3VydQo=                     #echo 'guru' | base64   output=Z3VydQo=
