apiVersion: v1
kind: Pod
metadata: 
    name: ip-cm
spec:
  containers:
    - name: ip-app
      image: gurubasavaraj/ip_app:latest
      ports:
      - containerPort: 80
      env:
      - name: DB_USER
        valueFrom:      
            secretKeyRef:                 #instead of configMapKeyRef here we use secretKeyRef
                name: my-secret           #objectname of the secret.yml we have mentioned 
                key: db_user              #Key we have mentioned in secret.yml we have given
      - name: DB_PASSWORD
        valueFrom:
            secretKeyRef:             
                name: my-secret
                key: db_pass       
                
