apiVersion: v1
kind: Pod
metadata: 
    name: request-limit
spec:
    containers:
    - name: ip-app
      image: gurubasavaraj/ip_app:latest
      ports:
      - containerPort: 80
      resources:
        requests:
          memory: "150Mi"
          cpu: "400m"
        limits:
          memory: "250Mi"
          cpu: "1000m"

