apiVersion: v1
kind: Pod
metadata:
    name: hostpathvolume 
spec: 
    containers:
    - name: ip-app 
      image: gurubasavaraj/ip_app:latest 
      ports:
      - containerPort: 80
      volumeMounts:
      - name: hostpath-vol
        mountPath: /etc/cont-vol
    volumes: 
    - name: hostpath-vol
      hostPath:
        path : /home/ubuntu/Allstars
        type: DirectoryOrCreate
    
