apiVersion: v1
kind: Pod
metadata:
    name: hostpath_volume 
spec: 
    containers:
    - name: ip-app 
      image: docker pull gurubasavaraj/ip_app:latest 
      ports:
      - containerPort: 80
      volumeMounts:
      - name: hostpath-vol
        mountPath: /app/cont-vol
    volumes: 
    - name: hostpath-vol
      hostPath:
         path : /home/ubuntu/pod
         type: DirectoryOrCreate
    