apiVersion: v1
kind: Service
metadata:
    name: my-nodeport-ip-app
spec:
    type: NodePort
    selector:
        app: ip-app
    ports:
      - name: http
        port: 8080
        targetPort: 8090
        nodePort: 31050

