apiVersion: batch/v1
kind: Job
metadata: 
    name: my-job
spec: 
    completions: 1
    backoffLimit: 2
    activeDeadlineSecond: 2
    template:
      spec:
        containers:
        - name: busybox
          image: gurubasavaraj/ip_app
          command:
          - /bin/sh
          - -c
          - "sleep 20; exit 1"
        restartPolicy: Never      
